### ISSUE TITLE
Applying colors to chart not working

### ISSUE THREAD

**Issue by uPloraX** [ConsoleTVs/Charts#137]
I wanted to apply custom colors to a chart within my controller function, but neither I tried is working.
Creating a default chart for example with `Charts::create('pie', 'chartjs')->...->colors(['#eee', '#ccc'])` or `Charts::multi(...)` doesn't work for me.
I tried multiple pairs with chartjs, material, highchart and your examples too, but neither worked.

Using version 4.0.5 (latest from composer).
Hope you can have a look into this.

**Comment by ConsoleTVs** [comment]
Use 4.0.8, seems I fixed it! I recommend you using templates rather than specifie the colors for each chart.

**Comment by uPloraX** [comment]
Yup, works like a charm now, thanks for your quick effort!

**Comment by ConsoleTVs** [comment]
You're welcome! small issues for bad code position :p

**Comment by mohitlandge** [comment]
Using consoletvs charts version 5 , still not able to change color of chart.


-->code is as follows.
    $chart = Charts::create('donut', 'c3')
                    ->colors(['purple', 'black'])
                    ->values([$count['complete_percent'], $count['incomplete_percent']])
                    ->dimensions(200, 250)
                    ->labels(["Completed", "Incomplete"])
                    ->responsive(false);

**Comment by ConsoleTVs** [comment]
Maybe you should stop using a charts version from 2017 (2 years ago) and start reading the new documentation of v6.
